// vue-frontend/src/components/Navbar.vue
<template>
    <nav class="bg-blue-600 text-white p-4">
      <div class="container mx-auto flex justify-between items-center">
        <div class="text-lg font-bold">WiFi Management</div>
        <ul class="flex space-x-4">
          <li><router-link to="/" class="hover:text-blue-200">Dashboard</router-link></li>
          <li><router-link to="/pelanggan" class="hover:text-blue-200">Pelanggan</router-link></li>
          <li><router-link to="/laporan" class="hover:text-blue-200">Laporan</router-link></li>
          <li><router-link to="/tagihan" class="hover:text-blue-200">Tagihan</router-link></li>
          <li><router-link to="/verifikasi-pembayaran" class="hover:text-blue-200">Verifikasi Pembayaran</router-link></li>
        </ul>
        <div class="flex items-center space-x-2">
          <span>Admin</span>
          <img src="https://via.placeholder.com/40" alt="Admin" class="rounded-full" />
        </div>
      </div>
    </nav>
  </template>
  
  <script>
  export default {
    name: "AppNavbar",
  };
  </script>

// next-frontend/src/components/Navbar.tsx
// src/app/components/Navbar.tsx
'use client';

import React from 'react';
import Link from 'next/link';

const Navbar = () => {
  return (
    <nav className="bg-primary text-white p-4 flex justify-between items-center">
      {/* Hamburger Menu */}
      <button className="md:hidden text-white text-xl">
        ☰
      </button>

      {/* Menu Items */}
      <div className="hidden md:flex space-x-4">
        <Link href="/dashboard" className="hover:text-gray-300">Dashboard</Link>
        <Link href="/pelanggan" className="hover:text-gray-300">Pelanggan</Link>
        <Link href="/tagihan" className="hover:text-gray-300">Tagihan</Link>
        <Link href="/paket" className="hover:text-gray-300">Paket</Link>
        <Link href="/verifikasi-pembayaran" className="hover:text-gray-300">Verifikasi Pembayaran</Link>
      </div>

      {/* Bell Icon */}
      <div className="text-xl">
        <Link href="/notifikasi" className="hover:text-gray-300">🔔</Link>
      </div>
    </nav>
  );
};

export default Navbar;
